server:
  port: 8082

spring:
  config:
    import: optional:file:.env[.properties]

# MCP 配置
mcp:
  amap_addr: ${AMAP_MAP_ADDR:https://mcp.api-inference.modelscope.net/0fceecf47ed541/sse}

# A2A协议服务端
agentscope:
  a2a:
    server:
      enabled: true
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
